### ISSUE TITLE
TODO: Learn page

### ISSUE THREAD

**Issue by caffeine-addictt** [python-thread/thread#90]
# Feature Request
Your issue may already be reported!
Please check out our [active issues](https://github.com/python-thread/thread.ngjx.org/issues) before creating one.

## Is Your Feature Request Related to an Issue?

Thread may appear overly confusing to use, especially for those unfamiliar with python's built-in threading library.
At present, there is no examples for usage of `thread`, providing these examples can help guide first-time developers.

## Describe the Solution You'd Like

A `'/learn' or equivalent` route should be created to provide easy-to-follow and heavily documented examples for using `thread`.

- [ ] Learn python threading module
- [ ] Learn thread package
- [x] Threading examples page
- [x] Parallel Processing examples page
- [x] Cautions pages
